CREATE DATABASE IF NOT EXISTS opencart20;
CREATE DATABASE IF NOT EXISTS opencart23;
CREATE DATABASE IF NOT EXISTS opencart3x;
CREATE DATABASE IF NOT EXISTS opencart4x;

GRANT ALL PRIVILEGES ON opencart20.* TO 'opencart'@'%';
GRANT ALL PRIVILEGES ON opencart23.* TO 'opencart'@'%';
GRANT ALL PRIVILEGES ON opencart3x.* TO 'opencart'@'%';
GRANT ALL PRIVILEGES ON opencart4x.* TO 'opencart'@'%';
FLUSH PRIVILEGES;
